FinishOnTime/urls.py
#rango
from django.conf.urls import url
from FinishOnTime import views
from django.conf.urls import include

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^index', views.index, name='index'),
	url(r'^library', views.library, name='library'),
	url(r'^project', views.project, name='project'),
	url(r'^add', views.add, name='add'),
	url(r'^edit', views.edit, name='edit'),
	url(r'^about', views.about, name='about'),
	url(r'^', include('registration.backends.simple.urls')),
]

finish_on_time/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf.urls import include
from FinishOnTime import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^FinishOnTime/', include('FinishOnTime.urls', namespace="FinishOnTime")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FinishOnTime/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

# Tool for naming urls
from django.template.defaultfilters import slugify

# Datetime tools 
from datetime import datetime

#1. Project
#    Title
#    Created
#    Deadline
#    Progress
class Project(models.Model):
	title = models.CharField(max_length=128, unique=True)
	created = models.DateTimeField(auto_now_add=True)
	deadline = models.DateTimeField()
	progress = models.IntegerField(default=0)
	slug = models.SlugField(unique=True)
	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Project, self).save(*args, **kwargs)

	def __str__(self): # For Python 2, use __unicode__ too
		return self.title
#2. Subtask
#    Project
#    Title
#    Deadline
#    Hours
#    Progress
class Subtask(models.Model):
	project = models.ForeignKey(Project)
	title = models.CharField(max_length=128)
	deadline = models.DateTimeField()
	hours = models.IntegerField(default=0)
	progress = models.BooleanField(default=False)
	level = models.CharField(max_length=1)

	def __str__(self): # For Python 2, use __unicode__ too
		return self.title
#3. Timeslot
class Timeslot(models.Model):
	timeslot_start = models.DateTimeField()
	timeslot_end = models.DateTimeField()
	timebetween = models.IntegerField()
	def save(self, *args, **kwargs):
		self.timebetween = (self.timeslot_end - self.timeslot_start)
		self.timebetween = int(self.timebetween.days * 24 * 3600 + self.timebetween.seconds)//60
		super(Timeslot, self).save(*args, **kwargs)

	def __str__(self): # For Python 2, use __unicode__ too
		return str(self.timebetween)

FinishOnTime/forms.py
from django import forms
import datetime
from django.contrib.auth.models import User
from FinishOnTime.models import Project, Subtask, Timeslot

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ('username', 'email', 'password')
		
class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ('title', 'deadline')
		
class SubtaskForm(forms.ModelForm):
	class Meta:
		model = Subtask
		fields = ('title', 'hours')
		
class TimeslotForm(forms.ModelForm):
	class Meta:
		model = Timeslot
		fields = ('timeslot_start', 'timeslot_end')

FinishOnTime/views.py
from django.shortcuts import render

# Dynamic data
# Import the Category model
from FinishOnTime.models import User, Project, Subtask, Timeslot

from FinishOnTime.forms import UserForm

from FinishOnTime.forms import ProjectForm, SubtaskForm, TimeslotForm

from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required

from datetime import datetime

# Create your views here.
from django.http import HttpResponse

def index(request):
	if request.method == 'POST':
		projectform = ProjectForm(request.POST)
		subtaskform = SubtaskForm(request.POST)
		timeslotform = Timeslot(request.POST)
		if index_form.is_valid():
			pass
	else: 
		projectform = ProjectForm()
		subtaskform = SubtaskForm()
		timeslotform = TimeslotForm()
	return render(request, 'FinishOnTime/index.html', {'projectform': projectform,'subtaskform': subtaskform,'timeslotform': timeslotform})
	
@login_required
def library(request):
	context_dict = {}
	return render(request, 'FinishOnTime/library.html', context_dict)
@login_required
def project(request):
	context_dict = {}
	return render(request, 'FinishOnTime/project.html', context_dict)
@login_required
def add(request):
	form = ProjectForm()
	# A HTTP POST?
	if request.method == 'POST':
		form = ProjectForm(request.POST)
		# Have we been provided with a valid form?
		if form.is_valid():
			# Save the new category to the database.
			form.save(commit=True)
			# Now that the category is saved
			# We could give a confirmation message
			# But since the most recent category added is on the index page
			# Then we can direct the user back to the index page.
			return index(request)
		else:
			# The supplied form contained errors -
			# just print them to the terminal.
			print(form.errors)
	# Will handle the bad form, new form, or no form supplied cases.
	# Render the form with error messages (if any).
	return render(request, 'FinishOnTime/add.html', {'form':form})
@login_required
def edit(request):
	context_dict = {}
	return render(request, 'FinishOnTime/edit.html', context_dict)
def about(request):
	context_dict = {}
	return render(request, 'FinishOnTime/about.html', context_dict)

templates/FinishOnTime/about.html
{% extends 'FinishOnTime/base.html' %}
{% load staticfiles %}

{% block body %}
<h2>Website "FinishOnTime"</h2>
<p>Developed by: Domantas Jonas Sakalys</p>
<p>Technologies used: Django</p>
<p>This website was developed as a second year project for Web Application Development 2 course</p>
{% endblock %}

templates/FinishOnTime/add.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}
	<h2>Add a new project</h2>
	<form id="project_form" method="post" action="{% url 'index' %}">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
			{{ hidden }}
		{% endfor %}
		{% for field in form.visible_fields %}
			{{ field.errors }}
			{{ field.help_text }}
			{{ field }}
		{% endfor %}
		<input type="submit" name="submit" value="Create Project" />
	</form>
{% endblock %}

templates/FinishOnTime/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}FinishOnTime{% endblock %}</title>
    {% load staticfiles %}
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'FinishOnTime:index' %}">FinishOnTime</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'FinishOnTime:index' %}">Home</a></li>
                <li><a href="{% url 'FinishOnTime:about' %}">About</a></li>
            </ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#">Log In</a></li>
				<li><a href="#">Register</a></li>
			</ul>
        </div>

    </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/FinishOnTime/edit.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}
{% endblock %}

templates/FinishOnTime/index.html
{% extends 'FinishOnTime/base.html' %}
{% load staticfiles %}

{% block body %}
<h1>Index Page</h1>
	<form id="index_form" method="post" action=".">
		{% csrf_token %} 
	
		{{ projectform.as_p }}
		{{ subtask.as_p }}
		{{ timeslotform.as_p }}
	
		<input type="submit" name="submit" value="Generate the workplan" />
	</form>
		
		
{% endblock %}

templates/FinishOnTime/library.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}

{% endblock %}

templates/FinishOnTime/project.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

{# DAFQ IS DIS? { load FinishOnTime_template_tags } #}

<html>
	<head>
		<style>
			p {font-family:sans-serif;}
			h1 {font-family:sans-serif;}
			h2 {font-family:sans-serif;}
			a {font-family:sans-serif;}
		</style>
		<title>
			FinishOnTime - 
			{% block title_block %}
				Index
			{% endblock %}
		</title>
	</head>
	<body>
		{% block sidebar_block %}
		<div style="height:50px;">
			<div style="float:left; width:40%;">
				<a href="{% url 'index' %}">Index</a>
				<a href="{% url 'about' %}">About</a>
			{% if user.is_authenticated %}
				<a href="{% url 'library' %}">Library</a>
				<a href="{% url 'add' %}">Add</a>
			{% endif %}
			</div>
			<div style="text-align:center; width:20%; float:left; font-size:20px;">FinishOnTime</div>
			<div style="float:right; text-align:right; width:40%;">
				{% if user.is_authenticated %}
					<a href="{% url 'auth_logout' %}">Logout</a>
					<a href="{% url 'auth_password_change' %}">Change Password</a>
				{% else %}
					<a href="{% url 'auth_login' %}">Login</a>
					<a href="{% url 'registration_register' %}">Register</a>
				{% endif %}	
			</div>
		</div>
		{% endblock %}
		<div style="text-align:center;">
			{% block body_block %}
			
			{% endblock %}
		</div>
	</body>
</html>